# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hoGUsgtWd2l56W39ASfYsDGbKuy5vyT0
"""

import sentiment_module as s

print(s.sentiment("the movie was awesome really nice mix of action , comedy and romance"))
print(s.sentiment("This party was illogical non sense manisfesto. its leader is criminal and this party has resorted to bad practises"))